name: 機能要望 / Feature Request
description: こんな機能があったら嬉しい、という提案はこちら / Suggest an idea or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: どんな課題・不便がありますか？ / What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 提案する機能・解決策 / Proposed solution
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: 補足 / Additional context
